### ISSUE TITLE
Drain workers API needs to be implemented

### ISSUE THREAD

**Issue by allada** [TraceMachina/native-link#351]
We need a way to drain a specific worker, so no new jobs are scheduled on the worker.

We already have a "is_paused" flag, so this might be the right place:
https://github.com/TraceMachina/turbo-cache/blob/5e2e81af8999482fef202b50ee880509e8811e6f/cas/scheduler/worker.rs#L97

**Comment by steed924** [comment]
I'd like to start working from this issue.

**Comment by aaronmondal** [comment]
@steed924 Thanks a lot for taking this ❤️

If you're running into any issues please  let me know what inconveniences you encountered when working with the Turbo-Cache codebase as it's my goal to make DX for the codebase as good as possible 😇

**Comment by steed924** [comment]
@aaronmondal, @allada .  Thanks for your offer. 
Since I'm new to this project, I'd like to ask some questions to get my hands dirty in this project.
I found out that there are already functions declared to remove the worker with its id in `simple_scheduler.rs`.

Is _drain workers API_ mean just the API to make the worker's `is_paused` flag to `false`?

Sorry for my sillly question. Thanks.

https://github.com/TraceMachina/turbo-cache/blob/5e2e81af8999482fef202b50ee880509e8811e6f/cas/scheduler/simple_scheduler.rs#L129C1-L129C74
